# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a5a766a6474dc33bab0d646e52f9b37470d38ce38c6d7501c7ea9da2ffa94272c6346a1faad7d23a1cbf811f037dfb339eaa02ba0509df586e244504d45cfe2

test:
  secret_key_base: 257b1b58a687bce09fe44f9a9e9e72ef426c8cf8f8fd10d98f0a15aa81e6a3d952fbeb4e0d739cfde9333baa7f7af545ab19a25c5dce7aaf181eaf29a18283b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
